/**
 * Volume Summary Script
 * Shows all volume generated by bots and trade counts
 */

import { prisma } from '../lib/prisma'

async function main() {
  // Get all bot instances
  const bots = await prisma.botInstance.findMany({
    include: {
      _count: { select: { orders: true } }
    }
  })

  console.log('═══════════════════════════════════════════════════════════════')
  console.log('                    BOT VOLUME SUMMARY')
  console.log('═══════════════════════════════════════════════════════════════\n')

  let totalVolume = 0
  let totalOrders = 0

  for (const bot of bots) {
    const walletShort = bot.userWalletAddress.slice(0, 10) + '...'
    const status = bot.isRunning ? '🟢 RUNNING' : '🔴 STOPPED'

    console.log(`${walletShort} | ${bot.marketName} | ${bot.strategy}`)
    console.log(`   Status: ${status}`)
    console.log(`   Volume: $${bot.cumulativeVolume.toLocaleString()} / $${bot.volumeTargetUSDC.toLocaleString()}`)
    console.log(`   Orders: ${bot._count.orders}`)
    console.log(`   Progress: ${((bot.cumulativeVolume / bot.volumeTargetUSDC) * 100).toFixed(1)}%`)

    if (bot.activePositionSize) {
      console.log(`   📊 Open Position: ${bot.activePositionIsLong ? 'LONG' : 'SHORT'} @ $${bot.activePositionEntry?.toFixed(2)}`)
    }
    console.log('')

    totalVolume += bot.cumulativeVolume
    totalOrders += bot._count.orders
  }

  console.log('═══════════════════════════════════════════════════════════════')
  console.log(`TOTAL VOLUME GENERATED: $${totalVolume.toLocaleString()}`)
  console.log(`TOTAL ORDERS IN DATABASE: ${totalOrders}`)
  console.log('═══════════════════════════════════════════════════════════════')

  // Break down by wallet
  console.log('\n📊 VOLUME BY WALLET:\n')

  const walletVolume: Record<string, { volume: number, orders: number, markets: string[] }> = {}

  for (const bot of bots) {
    const existing = walletVolume[bot.userWalletAddress]
    if (!existing) {
      walletVolume[bot.userWalletAddress] = { volume: 0, orders: 0, markets: [] }
    }
    walletVolume[bot.userWalletAddress].volume += bot.cumulativeVolume
    walletVolume[bot.userWalletAddress].orders += bot._count.orders
    walletVolume[bot.userWalletAddress].markets.push(bot.marketName)
  }

  for (const [wallet, data] of Object.entries(walletVolume)) {
    console.log(`${wallet.slice(0, 10)}... | $${data.volume.toLocaleString()} | ${data.orders} orders | ${data.markets.join(', ')}`)
  }

  await prisma.$disconnect()
}

main().catch(console.error)
